version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - ITK_SNAP_SERVER_DATABASE_NAME=admin_db
      - ITK_SNAP_SERVER_DATABASE_USERNAME=admin_user
      - ITK_SNAP_SERVER_DATABASE_PASSWORD=
      - ITK_SNAP_SERVER_NOAUTH=1
    working_dir: /app/itk_snap_server
    command: ["/app/wait-for-it.sh", "db:5432", "--", "python", "app.py", "--server"]
  service:
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile
    depends_on:
      - app
    links:
      - app
    environment:
      - DSS_URL=http://app:8080
      - DSS_SERVICE_HASH=e0a316038e9cbe6a000e07c82758532a8863f51f
